In [1]:
import numpy as np

Creating array of datatype integer

In [3]:
array = np.array([1,2,3], dtype='int32')
print(array)

[1 2 3]


To check shape and datatype

In [4]:
print(array.shape)
print(array.dtype)

(3,)
int32


In [40]:
a = np.array([(1,2,3.5),(-2,13,1.05)])
print(a)

[[ 1.    2.    3.5 ]
 [-2.   13.    1.05]]


Getting specific element

In [45]:
print(a[0, 2]) #first row, third element

3.5


Getting specific row

In [42]:
r=a[1, :] #second row
print(r)

[-2.   13.    1.05]


Getting specific column

In [43]:
c=a[:, 2] #third column
print(c)

[3.5  1.05]


In [44]:
print(a[1, :2]) # Second Row, two values

[-2. 13.]


Changing data

In [17]:
a[1,1] = -2

a[:,0] = [11,12]
print(a)

[[11.  2.  1.]
 [12. -2.  2.]]


3-D example

In [18]:
d = np.array([[[1,3,11],[5,0,7]],[[10,8,9],[10,-11,2]],[[13,5,9],[10,21,1]]])

print(d.shape) #dimension,row,column
print(d)

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(b.shape)
print(b)

(3, 2, 3)
[[[  1   3  11]
  [  5   0   7]]

 [[ 10   8   9]
  [ 10 -11   2]]

 [[ 13   5   9]
  [ 10  21   1]]]
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Zeros matrix

In [25]:
z=np.zeros((1,2,3),dtype='int32')
print(z)

[[[0 0 0]
  [0 0 0]]]


Ones matrix

In [26]:
o=np.ones((2,2,3),dtype='int32')
print(o)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


Random Matrix(int values)

In [28]:
r=np.random.randint(-10,10, size=(4,3))
print(r)

[[ -6 -10   4]
 [  8   0 -10]
 [ -8   9  -6]
 [ -2   0  -8]]


Copying arrays

In [30]:
a = np.array([1,2,3])
c = a.copy()
c[0] = 10

print(a)
print(c)

[1 2 3]
[10  2  3]


Reshaping

In [31]:
r = np.array([(1,2,3),(4,5,6)]) #2 rows 3 columns
print(r)
r=r.reshape(3,2) #3 rows 2 columns
print(r)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


Array object containing evenly spaced values within a defined interval.

In [32]:
a=np.arange(1,5)#default step value 1
b=np.arange(1,20,5)

print(a)
print(b)

[1 2 3 4]
[ 1  6 11 16]


Linspace gives evenly spaced samples.

In [37]:
l=np.linspace(1.0,50.0, num=20)
print(l)

[ 1.          3.57894737  6.15789474  8.73684211 11.31578947 13.89473684
 16.47368421 19.05263158 21.63157895 24.21052632 26.78947368 29.36842105
 31.94736842 34.52631579 37.10526316 39.68421053 42.26315789 44.84210526
 47.42105263 50.        ]


In [48]:
a = np.array([1.5,2.9,3.4,4.7,5.2])

print(np.min(a)) #minimum
print(np.max(a)) #maximum
print(np.mean(a)) #mean value
print(np.median(a)) #median
print(np.std(a)) #standard deviation


1.5
5.2
3.54
3.4
1.3184839779079607


In [49]:
print(a+2)
print(a-2)
print(a/2)
print(a*2)

b = np.array([10.1,0,7.9,1,5.9])
print(a+b)

[3.5 4.9 5.4 6.7 7.2]
[-0.5  0.9  1.4  2.7  3.2]
[0.75 1.45 1.7  2.35 2.6 ]
[ 3.   5.8  6.8  9.4 10.4]
[11.6  2.9 11.3  5.7 11.1]


Dot product

In [51]:
f = np.array([1,2])
g = np.array([3,4])
print(np.dot(f, g))

11


Mtrix Multiplication

In [53]:
h = [[1,2],[5,6]] 
i = [[3,4],[7,8]] 
print(np.matmul(h, i))

[[17 20]
 [57 68]]


Inverse of matrix

In [55]:
a = np.array([[3, 2, 1],
              [-14, -2, 5],
              [2, 0, 7]])
  
print(np.linalg.inv(a))
print(np.linalg.det(a))

[[-0.07865169 -0.07865169  0.06741573]
 [ 0.60674157  0.10674157 -0.16292135]
 [ 0.02247191  0.02247191  0.12359551]]
177.99999999999997


Rank of matrix

In [56]:
r = np.array([[0,0,1],[2,1,1],[4,5,4]])
print(np.linalg.matrix_rank(r))

3


Eigenvector and Eigenvalues

In [60]:
e = np.array([[1,2,3,4],[-5,-6,-7,-8],[9,10,11,12],[-1,-2,-3,-4]])
va, ve = np.linalg.eig(e)
print(va,ve)

[ 4.00000000e+00+0.00000000e+00j -2.00000000e+00+0.00000000e+00j
  6.21869165e-16+2.34835113e-16j  6.21869165e-16-2.34835113e-16j] [[ 0.20306923+0.j          0.5       +0.j         -0.29428964-0.14608249j
  -0.29428964+0.14608249j]
 [-0.50767308+0.j         -0.5       +0.j          0.65460452+0.j
   0.65460452-0.j        ]
 [ 0.81227693+0.j          0.5       +0.j         -0.42634011+0.43824746j
  -0.42634011-0.43824746j]
 [-0.20306923+0.j         -0.5       +0.j          0.06602523-0.29216498j
   0.06602523+0.29216498j]]
